### ISSUE TITLE
Task: 完善文档资料

### ISSUE THREAD

**Issue by Shareong** [WeBankBlockchain/WeCross#263]
如果你在了解、体验或使用WeCross时发现相关文献资料如[技术文档](https://wecross.readthedocs.io/zh_CN/dev/docs/tutorial/demo.html)、[白皮书](https://mp.weixin.qq.com/s/w0APEAonFXbOoinMJipPAA)、项目Readme有错误、不详、不妥等待改进的地方，欢迎提PR，社区由衷感谢你的贡献。

**Comment by Wuxiuga** [comment]
关于确认htlc合约跨链转账结果命令的一些疑问：
<img width="964" alt="截屏2020-11-16 下午8 31 48" src="https://user-images.githubusercontent.com/55292351/99256151-ec7bdd00-284f-11eb-8eb7-273942b00d13.png">这里bcos_user1是发起者，而后面的地址是bcos链上的转账接受者，是不是存在问题，还是在查询账户余额的命令就是这么规定的；相同的疑问还有fabric链上的fabric_admin的账户

**Comment by Shareong** [comment]
> 关于确认htlc合约跨链转账结果命令的一些疑问：
> <img alt="截屏2020-11-16 下午8 31 48" width="964" src="https://user-images.githubusercontent.com/55292351/99256151-ec7bdd00-284f-11eb-8eb7-273942b00d13.png">这里bcos_user1是发起者，而后面的地址是bcos链上的转账接受者，是不是存在问题，还是在查询账户余额的命令就是这么规定的；相同的疑问还有fabric链上的fabric_admin的账户

第一个账户是发交易的签名账户，和HTLC无关。关联Issue#398
