### ISSUE TITLE
Task: 用更优雅的姿势打印日志

### ISSUE THREAD

**Issue by Shareong** [WeBankBlockchain/WeCross#280]
所有debug和trace级别的日志打印姿势修改为:
```java
if (logger.isDebugEnabled()) {
    logger.debug(" debug log message ");
}

if (logger.isTraceEnabled()) {
    logger.trace(" trace log message ");
}
```

项目列表：

- [x] [WeCross-Router](https://github.com/WeBankFinTech/WeCross)

- [ ] [WeCross-BCOS-Stub](https://github.com/WeBankFinTech/WeCross-BCOS2-Stub)

- [ ] [WeCross-Fabric-Stub](https://github.com/WeBankFinTech/WeCross-Fabric1-Stub)

- [ ] [WeCross-Console](https://github.com/WeBankFinTech/WeCross-Console)

- [x] [WeCross-Java-Sdk](https://github.com/WeBankFinTech/WeCross-Java-SDK)

**Comment by chenjiawei514** [comment]
挑战

**Comment by JimmyShi22** [comment]
#357

**Comment by Shareong** [comment]
- [x] [WeCross-Router](https://github.com/WeBankFinTech/WeCross) done by #357  @chenjiawei514

**Comment by Shareong** [comment]
- [x] [WeCross-Router](https://github.com/WeBankFinTech/WeCross-Java-SDK) done by [91](https://github.com/WeBankFinTech/WeCross-Java-SDK/pull/91)  @chenjiawei514
