### ISSUE TITLE
Task: 项目构建偶尔有点慢，给它加个速吧

### ISSUE THREAD

**Issue by Shareong** [WeBankBlockchain/WeCross#343]
因为网络原因，构建项目下载依赖偶尔会出现卡顿。

试试把国内知名的maven仓库添加到`build.gradle`文件的`repositories`，问题可能就解决了哦。

项目列表：

- [x] [WeCross-Router](https://github.com/WeBankFinTech/WeCross)

- [ ] [WeCross-BCOS-Stub](https://github.com/WeBankFinTech/WeCross-BCOS2-Stub)

- [ ] [WeCross-Fabric-Stub](https://github.com/WeBankFinTech/WeCross-Fabric1-Stub)

- [ ] [WeCross-Console](https://github.com/WeBankFinTech/WeCross-Console)

- [ ] [WeCross-Java-Sdk](https://github.com/WeBankFinTech/WeCross-Java-SDK)

**Comment by chendongcse** [comment]
挑战

**Comment by Shareong** [comment]
- [x] [WeCross-Router](https://github.com/WeBankFinTech/WeCross) done by #352 @chendongcse
