### ISSUE TITLE
Task: 控制台发交易和执行事务的命令容易混淆，需要一个更好的命名

### ISSUE THREAD

**Issue by Shareong** [WeBankBlockchain/WeCross#348]
发交易的命令叫sendTransaction，两阶段事务中执行一个事务步骤（本质还是发交易）叫execTransaction，如果有更好的命名方式，请留言。

**Comment by chendongcse** [comment]
挑战。
两阶段事务提交中第一轮叫 prepareTransaction 或者  queryToCommitTransaction 怎么样？

**Comment by chenjiawei514** [comment]
startTransaction

**Comment by Shareong** [comment]
> 挑战。
> 两阶段事务提交中第一轮叫 prepareTransaction 或者 queryToCommitTransaction 怎么样？

目前控制台两阶段的相关命令有：startTransaction、execTransaction、commitTransaction、rollbackTransaction。
真正纠结的地方在于，交易和事务都用Transaction是否合理，以及如何在代码里区分。

**Comment by Shareong** [comment]
> startTransaction

这个控制台已经有了，start是启动两阶段事务的命令。

**Comment by 767472021** [comment]
startProposal、execProposal、commitProposal、rollbackProposal
