### ISSUE TITLE
跨链转账结果确认出现问题

### ISSUE THREAD

**Issue by Wuxiuga** [WeBankBlockchain/WeCross#398]
**BUG描述**
按照文档进行htlc跨链转账操作：在进行转账结果确认时发现，bcos_user1(发起者)账户余额确实发生了变化（减少700），但是bcos_user2(bcos链上的转账接受者)账户余额仍是0；查询fabric_user1（fabric链上的转账接受者）账户余额增加500，但是fabric_admin的账户余额却未发生变化。很是费解，希望我描述的算清楚，附上截图
<img width="1401" alt="截屏2020-11-16 下午9 26 14" src="https://user-images.githubusercontent.com/55292351/99258712-eee03600-2853-11eb-9516-1154fcf4e07f.png">
<img width="1401" alt="截屏2020-11-16 下午9 36 32" src="https://user-images.githubusercontent.com/55292351/99258848-1f27d480-2854-11eb-8fd6-d76052d31875.png">

**重现方式**

**预期结果**
详细描述上述操作的预期结果。

**截图**
如果可行，放上截图便于更具体地描述BUG。

**环境**
 - 操作系统: [例如 Ubuntu、CentOS、MACOS]
 - 运行库 [例如 libc, java ]
 - 版本 [操作系统和运行库的版本]

**更多信息**
关于该 BUG 的更多信息

**Comment by JimmyShi22** [comment]
HTLC转账未成功，可以看下两个router的logs/error.log

**Comment by Shareong** [comment]
问题1：为何转账后Fabric的转出者资金并没有变化。
由于Fabric没有合约账户，且没有官方资产模型，因此我们自己撸了一个可配合HTLC的示例账本LedgerSample。资产授权是通过把资金转移到一个托管账户，因此在HTLC流程中，发送方扣的都是托管账户里的钱。
问题2：这个需要结合日志分析，为何BCOS链的资产没被解锁。
