### ISSUE TITLE
bulid demo error: WeCross-Account-Manager start failed

### ISSUE THREAD

**Issue by KunPengRen** [WeBankBlockchain/WeCross#456]
Hi, there.
I am a new user for wecross. When I built the demo build_cross_all.sh, it returns the below error:

WeCross-Account-Manager start failed
See logs/error.log for details
Error log
2020-12-24 16:17:45.030 [main] ERROR SqlExceptionHelper() - Communications link failure
.....................................
Initializing TomcatServletWebServerFactory: Service{address='0.0.0.0', port=8340, sslKey='classpath:ssl.key', sslCert='classpath:ssl.crt', caCert='classpath:ca.crt', sslOn=true}
Hibernate: drop table if exists hibernate_sequence
ERROR: Database connection exception, please check!

Any requirement I need for fixing the error?

**Comment by morebtcg** [comment]
从错误来看是连接数据库出错了，检查一下数据库的状态是否正常

**Comment by KunPengRen** [comment]
problem solved, install MySQL in my macos and tested ok.
My Linux pc may configure MySQL failed.
