### ISSUE TITLE
mac可能出现的bug，显示fabric/fabric-samples-1.4.4/first-network/base/peer-base.yaml有格式问题。可以在这里加6次'\'和‘ ’交替

### ISSUE THREAD

**Issue by ccznb** [WeBankBlockchain/WeCross#518]
https://github.com/WeBankBlockchain/WeCross/blob/50cdb9d8f7280579a32edc49112da6c8228accbe/demo/fabric/build.sh#L80

**Comment by kyonRay** [comment]
关联PR #519
