### ISSUE TITLE
启动WeCross Account Manager失败

### ISSUE THREAD

**Issue by yngil** [WeBankBlockchain/WeCross#573]
**Describe the bug**
在手动组网时，启动WeCross Account Manager失败，问题附在log日志中。
[error.log](https://github.com/WeBankBlockchain/WeCross/files/11396739/error.log)

**To Reproduce**
1. cd ~/wecross-networks
2. cd ~/wecross-networks/WeCross-Account-Manager/
3. cp ~/wecross-networks/routers-payment/cert/sdk/* conf/
4. bash create_rsa_keypair.sh -d conf/
5. cp conf/application-sample.toml conf/application.toml
6. vim conf/application.toml
7. bash start.sh

**Expected behavior**
期待可以看到应用启动无异常

**Screenshots**
![image](https://user-images.githubusercontent.com/7745583/236187556-9b72fdf9-123b-42e9-8ff1-921d0debcc32.png)

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Runtime: [java]
 - Version [openjdk 1.8.0_312]

**Additional context**

**Comment by kyonRay** [comment]
请提供一下本地openssl的版本号，以及本地WeCross Account Manager的版本号。这个问题应该是上述步骤的第4步生成rsa密钥对加载失败引起的。

**Comment by yngil** [comment]
问题已解决，原因是macos的openssl版本为libressl，修改为openssl@1.1版本后，应用可以正常启动
