### ISSUE TITLE
启动路由失败

### ISSUE THREAD

**Issue by yngil** [WeBankBlockchain/WeCross#574]
**Describe the bug**
启动路由时，提示连接失败

**To Reproduce**
1. 先启动账户服务 'cd ~/wecross-networks/WeCross-Account-Manager && bash start.sh'
2. 再启动路由服务 'cd ~/wecross-networks/routers-payment && bash start_all.sh'

**Expected behavior**
期待看到’WeCross start successfully‘

**Screenshots**
![image](https://user-images.githubusercontent.com/7745583/236388702-ff2eb37a-a12c-4407-8dc2-e02088316a31.png)

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Runtime: [ava]
 - Version [openjdk 11]

**Additional context**
账户服务已启动
![image](https://user-images.githubusercontent.com/7745583/236388431-00463580-f3b1-451f-ad63-f27b4f614910.png)
![image](https://user-images.githubusercontent.com/7745583/236388471-9d9e504b-3dd4-4316-a4ef-6f2dbafa4fd6.png)
附上账户服务以及路由的错误日志以及trace日志
[account_manager_trace.log](https://github.com/WeBankBlockchain/WeCross/files/11403719/account_manager_trace.log)
[router_8250_error.log](https://github.com/WeBankBlockchain/WeCross/files/11403722/router_8250_error.log)
[router_8250_trace.log](https://github.com/WeBankBlockchain/WeCross/files/11403724/router_8250_trace.log)

**Comment by kyonRay** [comment]
在x86 macOS 环境中如果跨链路由带上bcos3 stub，有可能因为系统版本过低而导致启动失败。

主要原因是bcos3 stub是用的fisco bcos java sdk 3.0版本，3.0版本内的jni二进制可能在x86的低版本macOS存在符号未定义导致加载失败的问题。

**Comment by kyonRay** [comment]
临时解决办法：将bcos3 stub从路由中删除，不主动加载即可。若一定需要使用bcos3 stub连接 FISCO BCOS 3.x版本，那么请升级macOS系统版本，升级Xcode命令行工具到最新。
