### ISSUE TITLE
we-cross demo部署过程中发现的问题

### ISSUE THREAD

**Issue by yamasakitetuya** [WeBankBlockchain/WeCross#585]
在部署we-cross demo过程中遇到的问题  

输入 `bash build_cross_all.sh`后，程序在输出Generating CA key...之后终止。
但是控制台没有关于错误信息的输出，请问可能是哪里出了问题？

但是终止后输入`bash clear.sh`后，显示

`WeCross isn't running`  
`WeCross isn't running`  
`Stop WeCross-Account-Manager successfully `   

jdk: java version "1.8.0_381"
mysql: 8.0.34
docker: 4.21.1
openssl: 1.1

**Comment by kyonRay** [comment]
能否给出更多的打印信息？可以在bash命令后面增加`-x`选项。有可能是在部署bcos链使用build_chain脚本时有错误推出的。

**Comment by yamasakitetuya** [comment]
感谢指正，这是具体的脚本执行情况。
<img width="728" alt="截屏2023-08-09 14 05 52" src="https://github.com/WeBankBlockchain/WeCross/assets/46259494/dd17c5aa-15f0-4422-8872-a66d5b718d54">

您说的本地部署bcos链是指这里的内容吗？  
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/installation.html

**Comment by yamasakitetuya** [comment]
补充：  
执行 https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/installation.html 中的部署流程时。   
出现同样的在输出` Generating CA key...`之后程序终止的问题。  
根据脚本执行详情，脚本最后执行到 
` gen_rsa_chain_cert agency /Users/leifwu/fisco/nodes/cert/agency/channel`

**Comment by kyonRay** [comment]
https://github.com/FISCO-BCOS/FISCO-BCOS/blob/83a87ad749475c0edcc6d5ce2dabd328a36d3bae/tools/build_chain.sh#L346-L347

**Comment by yamasakitetuya** [comment]
> > 补充： 执行 https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/installation.html 中的部署流程时。 出现同样的在输出` Generating CA key...`之后程序终止的问题。 根据脚本执行详情，脚本最后执行到 ` gen_rsa_chain_cert agency /Users/leifwu/fisco/nodes/cert/agency/channel`
> 
> 这个结果是bash -x build_chain.sh得出的吗？尝试执行一下 `openssl version` 看看结果。应该是openssl版本不对。

输入`bash -x build_chain.sh -l 127.0.0.1:4 -p 30300,20200,8545` 后， 

程序终止于：  

<img width="799" alt="截屏2023-08-09 16 16 42" src="https://github.com/WeBankBlockchain/WeCross/assets/46259494/f4a03976-a37c-4901-8de8-ef464b97ace3">

当前openssl 版本为 OpenSSL 1.1.1v  1 Aug 2023。

必须使用主页上的OpenSSL 1.1.1n 版本吗？😹

**Comment by yamasakitetuya** [comment]
_当Openssl的版本只有1.1.1时_
这个时候fisco-bcos网络是可以构建的，但是在运行demo时出现了错误输出：  

> dyld[6023]: Library not loaded: '/usr/local/opt/openssl@3/lib/libssl.3.dylib'
  Referenced from: '/usr/local/Cellar/md5sha1sum/0.9.5_1/bin/md5sum'
  Reason: tried: '/usr/local/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file)
download_wecross.sh: line 126:  6023 Abort trap: 6           md5sum -c ${release_pkg_checksum_file}
[ERROR] Download package error.

说明demo的运行还是需要openssl@3的，  
因此这个时候使用`brew install openssl@3`安装。

出现了报错信息，但是`brew list`输出显示已安装。  
猜测报错原因是因为我已经在/usr/local/bin中创建了指向opensl@1.1.1的symbollink。  

>==> Pouring openssl@3-3.1.2.monterey.bottle.1.tar.gz
Error: same file: /usr/local/bin/openssl and /Users/leifwu/Library/Caches/Homebrew/Backup/bin/openssl/openssl

_Solution_
1. 将openssl@1.1和openssl@3一起用homebrew卸载
2. 重新安装openssl@1.1和openssl@3，此时/usr/local/bin/openssl是指向openssl@3安装路径的symbollink。
3. 将/usr/local/bin/openssl改成指向openssl@1.1的symbollink后，问题解决。

**Comment by yamasakitetuya** [comment]
在卸载openssl@1.1和openssl@3之前发现一个奇怪的问题：  

当我把下面的代码末尾的 `2>/dev/null`注释掉后， 尝试本地部署bcos链时， 
build.log里出现了关于调用不到openssl@3的组件的错误信息，但是当时`openssl version`的输出是 OpenSSL 1.1.1v 1 Aug 2023  
尚不明确这个错误出现的原因。


`openssl genrsa -out "${chaindir}"/ca.key "${rsa_key_length}" 2>/dev/null`
`openssl req -new -x509 -days "${days}" -subj "/CN=${name}/O=fisco-bcos/OU=chain" -key "${chaindir}"/ca.key -out "${chaindir}"/ca.crt  2>/dev/null`

**Comment by kyonRay** [comment]
应该是openssl@3没有卸载干净，可以搜索一下相关问题。
