### ISSUE TITLE
fabric2.3部署跨链合约时报错

### ISSUE THREAD

**Issue by gm100861** [WeBankBlockchain/WeCross#598]
**BUG描述**
在部署跨链合约时报错
```
[WeCross.org1-admin]> fabricInstall payment.fabric2.interchain org2 contracts/chaincode/interchain 1.0 G0_LANG
path: classpath:contracts/chaincode/interchain
Error: code(10000), message(Query to orgPeers:[Peer{ id: 2, name: peer1, channelName: mychannel, url: grpcs://localhost:9051}] endorser failed: Success endorser: 0 Failed endorser: 1["peer: peer1 status: FAILURE message: failed to invoke backing implementation of 'InstallChaincode': could not parse as a chaincode install package: did not find a code package inside the package", ] payloads:size: 0 [] proposal response consistency: proposalResponses collection is empty)
```

看了一下Fabric的日志，如下
```
2023-12-12 06:40:19.298 UTC [chaincode.persistence] Parse -> WARN 19cf Encountered unexpected file 'src/chaincode/interchainSample.go' in top level of chaincode package
2023-12-12 06:40:19.298 UTC [endorser] callChaincode -> INFO 19d0 finished chaincode: _lifecycle duration: 0ms channel=mychannel txID=ae7b6d8b
```

**重现方式**
重现 BUG 的操作步骤。
例如：
1.按照官方操作文档搭建环境，使用的Fabric版本是2.X的版本，看了下应该是2.3.X，使用的也是官方提供的脚本
2.在console中部署跨链合约，会报错。我的跨链环境已经是正常的了

**预期结果**
应该能正常部署跨链合约

**截图**
![image](https://github.com/WeBankBlockchain/WeCross/assets/3993839/5bd036d6-9892-4da8-9cf7-20798a2df6df)
![image](https://github.com/WeBankBlockchain/WeCross/assets/3993839/ffa55b44-bb66-4665-88d6-3cc3b5785e35)

**环境**
 - 操作系统: CentOS Linux release 7.5.1804 (Core) 
```
# java -version
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (build 1.8.0_392-b08)
OpenJDK 64-Bit Server VM (build 25.392-b08, mixed mode)
```

**更多信息**
看console代码里面，有一个写死的路径，fabric1.4是好的，不知道2.3是不是这个路径会有问题
![image](https://github.com/WeBankBlockchain/WeCross/assets/3993839/e6b18f59-0540-4618-8086-0ccb3a3437bf)

**Comment by kyonRay** [comment]
WeCross目前还是不支持通过控制台或者网页观礼台部署合约，请参考：https://github.com/WeBankBlockchain/WeCross-Fabric2-Stub/releases/tag/v1.2.0

**Comment by gm100861** [comment]
> WeCross目前还是不支持通过控制台或者网页观礼台部署合约，请参考：https://github.com/WeBankBlockchain/WeCross-Fabric2-Stub/releases/tag/v1.2.0

好的，谢谢
